# Generated by Django 2.1.7 on 2019-03-31 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_data',
            new_name='contact_date',
        ),
    ]
