state_choices ={
'AP':'Andra Pradesh'
'AR':'Arunachal Pradesh'
'AS':'Assam'
'BH':'Bihar'
'CH':'Chhattisgarh'
'GO':'Goa'
'GJ':'Gujarat'
'HY':'Haryana'
'HP':'Himachal Pradesh'
'JK':'Jammu & Kasmir'
'JH':'Jharkand'
'KA':'Karnataka'
'KL':'Kerala'
'MP':'Madhya Pradesh'
'MH':'Maharastra'
'MN':'Manipur'
'MG':'Meghalaya'
'MZ':'Mizoram'
'NG':'Nagaland'
'OD':'Odisha'
'PJ':'Punjab'
'RJ':'Rajasthan'
'SI':'Sikkim'
'TN':'Tamil Nadu'
'TE':'Telangana'
'TR':'Tripura'
'UP':'Uttar Pradesh'
'UT':'Uttarakhand'
'WB':'West Bengal'
'AN':'Andaman Nicobar'
'CG':'Chandigarh'
'DN':'Dadra and Nagar Haveli'
'DD':'Daman and Diu'
'DL':'Delhi'
'LD':'Lakshadweep'
'PU':'Puducherry'
}