state_choices ={
'Andra Pradesh':'Andra Pradesh',
'Arunachal Pradesh':'Arunachal Pradesh',
'Assam':'Assam',
'Bihar':'Bihar',
'Chhattisgarh':'Chhattisgarh',
'Goa':'Goa',
'Gujarat':'Gujarat',
'Haryana':'Haryana',
'Himachal Pradesh':'Himachal Pradesh',
'Jammu & Kasmir':'Jammu & Kasmir',
'Jharkand':'Jharkand',
'Karnataka':'Karnataka',
'Kerala':'Kerala',
'Madhya Pradesh':'Madhya Pradesh',
'Maharastra':'Maharastra',
'Manipur':'Manipur',
'Meghalaya':'Meghalaya',
'Mizoram':'Mizoram',
'Nagaland':'Nagaland',
'Odisha':'Odisha',
'Punjab':'Punjab',
'Rajasthan':'Rajasthan',
'Sikkim':'Sikkim',
'Tamil Nadu':'Tamil Nadu',
'Telangana':'Telangana',
'Tripura':'Tripura',
'Uttar Pradesh':'Uttar Pradesh',
'Uttarakhand':'Uttarakhand',
'West Bengal':'West Bengal',
'Andaman Nicobar':'Andaman Nicobar',
'Chandigarh':'Chandigarh',
'Dadra and Nagar Haveli':'Dadra and Nagar Haveli',
'Daman and Diu':'Daman and Diu',
'Delhi':'Delhi',
'Lakshadweep':'Lakshadweep',
'Puducherry':'Puducherry'
}

bedroom_choices={
    '1':1,
    '2':2,
    '3':3,
    '4':4,
    '5':5,
    '6':6,
    '7':7,
    '8':8,
    '9':9,
    '10':10
}
price_choices={
'100000':'₹100,000',
'200000':'₹200,000',
'300000':'₹300,000',
'400000':'₹400,000',
'500000':'₹500,000',
'600000':'₹600,000',
'700000':'₹700,000',
'800000':'₹800,000',
'900000':'₹900,000'
}